version: '2.2'

services:
  web:
    image: azuracast/azuracast_web_v2:latest
    build:
      context: ../docker-azuracast-web-v2
    # Want to customize the HTTP/S ports? Follow the instructions here:
    # https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#use-non-standard-ports
    ports:
      - '${AZURACAST_HTTP_PORT:-9990}:9990'
      - '${AZURACAST_HTTPS_PORT:-9995}:9995'
    depends_on:
      - mariadb
      - influxdb
      - stations
      - redis
    env_file: azuracast.env
    environment: &default-environment
      LANG: ${LANG:-en_US.UTF-8}
      AZURACAST_DC_REVISION: 5
    volumes:
      - letsencrypt:/etc/letsencrypt
      - .:/var/azuracast/www
      - tmp_data:/var/azuracast/www_tmp
      - station_data:/var/azuracast/stations
      - shoutcast2_install:/var/azuracast/servers/shoutcast2
      - backups:/var/azuracast/backups
    restart: always
    ulimits: &default-ulimits
      nofile:
        soft: 65536
        hard: 65536
    logging: &default-logging
      options:
        max-size: "1m"
        max-file: "5"

  mariadb:
    image: azuracast/azuracast_db:latest
    build:
      context: ../docker-azuracast-db
    ports:
     - "127.0.0.1:3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file: azuracast.env
    environment:
      << : *default-environment
    restart: always
    logging: *default-logging

  influxdb:
    image: azuracast/azuracast_influxdb:latest
    build:
      context: ../docker-azuracast-influxdb
    volumes:
      - influx_data:/var/lib/influxdb
    restart: always
    logging: *default-logging

  redis:
    image: azuracast/azuracast_redis:latest
    build:
      context: ../docker-azuracast-redis
    ports:
     - "127.0.0.1:6379:6379"
    restart: always
    logging: *default-logging
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - redis_data:/data

  stations:
    container_name: azuracast_stations
    image: azuracast/azuracast_radio:latest
    build:
      context: ../docker-azuracast-radio
    ports:
     - '10010:10010'
     - '10005:10005'
     - '10006:10006'
     - '10010:10010'
     - '10015:10015'
     - '10016:10016'
     - '10020:10020'
     - '10025:10025'
     - '10026:10026'
     - '10030:10030'
     - '10035:10035'
     - '10036:10036'
     - '10040:10040'
     - '10045:10045'
    volumes:
     - station_data:/var/azuracast/stations
     - letsencrypt:/etc/nginx/ssl:ro
     - shoutcast2_install:/var/azuracast/servers/shoutcast2
     - tmp_data:/var/azuracast/www_tmp
    init: true
    restart: always
    ulimits: *default-ulimits
    logging: *default-logging

#  chronograf:
#    image: chronograf:alpine
#    ports:
#     - "8888:8888"
#    command: "chronograf --influxdb-url=http://influxdb:8086"

#  redis-commander:
#    image: rediscommander/redis-commander:latest
#    depends_on:
#    - redis
#    environment:
#      REDIS_HOSTS: "local-app:redis:6379:0,local-sessions:redis:6379:1,local-doctrine:redis:6379:2"
#    ports:
#    - "127.0.0.1:8081:8081"

#  blackfire:
#    image: blackfire/blackfire
#    environment:
#      BLACKFIRE_SERVER_ID: ""
#      BLACKFIRE_SERVER_TOKEN: ""

volumes:
  letsencrypt: {}
  db_data: {}
  influx_data: {}
  station_data: {}
  shoutcast2_install: {}
  tmp_data: {}
  redis_data: {}
  backups: {}
