#
# AzuraCast Docker Compose Configuration File
#
# When updating, you will be prompted to replace this file with a new
# version; you should do this whenever possible to take advantage of
# new updates.
#
# If you need to customize this file, you can create a new file named:
#   docker-compose.override.yml
# with any changes you need to make.
#
version: '2.2'

services:
  web:
    image: azuracast/azuracast_web_v2:latest
    # Want to customize the HTTP/S ports? Follow the instructions here:
    # https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#use-non-standard-ports
    ports:
      - '${AZURACAST_HTTP_PORT:-9990}:9990'
      - '${AZURACAST_HTTPS_PORT:-9995}:9995'
    depends_on:
      - mariadb
      - influxdb
      - stations
      - redis
    env_file: azuracast.env
    environment: &default-environment
      LANG: ${LANG:-en_US.UTF-8}
      AZURACAST_DC_REVISION: 5
    volumes:
      - letsencrypt:/etc/letsencrypt
      - www_data:/var/azuracast/www
      - tmp_data:/var/azuracast/www_tmp
      - station_data:/var/azuracast/stations
      - shoutcast2_install:/var/azuracast/servers/shoutcast2
      - backups:/var/azuracast/backups
    restart: always
    ulimits: &default-ulimits
      nofile:
        soft: 65536
        hard: 65536
    logging: &default-logging
      options:
        max-size: "1m"
        max-file: "5"

  mariadb:
    image: azuracast/azuracast_db:latest
    volumes:
      - db_data:/var/lib/mysql
    env_file: azuracast.env
    environment:
      <<: *default-environment
    restart: always
    logging: *default-logging

  influxdb:
    image: azuracast/azuracast_influxdb:latest
    volumes:
      - influx_data:/var/lib/influxdb
    restart: always
    logging: *default-logging

  redis:
    image: azuracast/azuracast_redis:latest
    restart: always
    logging: *default-logging
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - redis_data:/data

  stations:
    container_name: azuracast_stations
    image: azuracast/azuracast_radio:latest
    ports:
    # This default mapping is the outgoing and incoming ports for the first 50 stations.
    # You can override this port mapping in your own docker-compose.override.yml file.
    # For instructions, see:
    # https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#expand-the-docker-radio-station-port-range
     - '10010:10010'
     - '10005:10005'
     - '10006:10006'
     - '10010:10010'
     - '10015:10015'
     - '10016:10016'
     - '10020:10020'
     - '10025:10025'
     - '10026:10026'
     - '10030:10030'
     - '10035:10035'
     - '10036:10036'
     - '10040:10040'
     - '10045:10045'
    volumes:
     - station_data:/var/azuracast/stations
     - shoutcast2_install:/var/azuracast/servers/shoutcast2
     - letsencrypt:/etc/nginx/ssl:ro
     - tmp_data:/var/azuracast/www_tmp
    init: true
    restart: always
    ulimits: *default-ulimits
    logging: *default-logging

volumes:
  db_data: {}
  influx_data: {}
  letsencrypt: {}
  shoutcast2_install: {}
  station_data: {}
  tmp_data: {}
  www_data: {}
  redis_data: {}
  backups: {}
